# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 20:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 26, 20, 20, 48, 808297)),
        ),
    ]
