# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20171023_0003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Budget_Items',
            new_name='Item',
        ),
    ]
