# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 23:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20171031_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime(2017, 10, 31, 23, 22, 23, 561050))),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Bank')),
            ],
        ),
        migrations.RemoveField(
            model_name='income',
            name='bank',
        ),
        migrations.AddField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 31, 23, 22, 23, 561414)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 31, 23, 22, 23, 561825)),
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
