# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20171023_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='Item_name',
            field=models.CharField(max_length=20),
        ),
    ]
