# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20171023_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='Description',
        ),
    ]
