# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20171023_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='value',
            new_name='Value',
        ),
    ]
