# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 23:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_auto_20171109_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='debt',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 9, 23, 30, 34, 178729)),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 9, 23, 30, 34, 178292)),
        ),
    ]
