# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 23:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_auto_20171109_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='remain',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 9, 23, 47, 42, 389378)),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 9, 23, 47, 42, 388954)),
        ),
    ]
