# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 19:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_auto_20171109_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 10, 19, 55, 44, 174558)),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 10, 19, 55, 44, 173565)),
        ),
    ]
