# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 20:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_auto_20171110_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomes',
            name='remain',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 10, 20, 2, 12, 116244)),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 10, 20, 2, 12, 115817)),
        ),
    ]
