# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 12:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_auto_20171110_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='incomes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Incomes'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 12, 12, 32, 40, 712217)),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.LivingCost'),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 12, 12, 32, 40, 711784)),
        ),
    ]
