# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_auto_20171112_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='incomes',
            new_name='income',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 12, 12, 34, 44, 902798)),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 12, 12, 34, 44, 901786)),
        ),
    ]
