# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 12:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_auto_20171112_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='income',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Incomes'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 12, 12, 40, 20, 653484)),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 12, 12, 40, 20, 653048)),
        ),
    ]
