# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 12:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_auto_20171112_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 12, 12, 48, 32, 167049)),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 12, 12, 48, 32, 166614)),
        ),
    ]
