# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 23:05
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0019_auto_20171112_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='ratio',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 23, 5, 37, 518418)),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 23, 5, 37, 517826)),
        ),
    ]
