# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 23:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0021_auto_20171113_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomes',
            name='livingcost',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 23, 14, 33, 20282)),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 23, 14, 33, 16131)),
        ),
    ]
