# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 23:37
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0025_auto_20171113_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='ratio',
            field=models.FloatField(default=0.6, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 23, 37, 8, 265681)),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 23, 37, 8, 265087)),
        ),
        migrations.AlterField(
            model_name='livingcost',
            name='ratio',
            field=models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
