# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 19:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0026_auto_20171113_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='category',
            field=models.CharField(choices=[('Food', '食'), ('Clothing', '衣'), ('Accommodation', '住'), ('Transportation', '行'), ('Education', '育'), ('Entertainment', '樂'), ('Deposit', '存款'), ('Investment', '投資')], default='Food', max_length=30),
        ),
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('Food', '食'), ('Clothing', '衣'), ('Accommodation', '住'), ('Transportation', '行'), ('Education', '育'), ('Entertainment', '樂'), ('Deposit', '存款'), ('Investment', '投資')], default='Food', max_length=30),
        ),
        migrations.AddField(
            model_name='debt',
            name='category',
            field=models.CharField(choices=[('Food', '食'), ('Clothing', '衣'), ('Accommodation', '住'), ('Transportation', '行'), ('Education', '育'), ('Entertainment', '樂'), ('Deposit', '存款'), ('Investment', '投資')], default='Food', max_length=30),
        ),
        migrations.AddField(
            model_name='deposit',
            name='category',
            field=models.CharField(choices=[('Food', '食'), ('Clothing', '衣'), ('Accommodation', '住'), ('Transportation', '行'), ('Education', '育'), ('Entertainment', '樂'), ('Deposit', '存款'), ('Investment', '投資')], default='Food', max_length=30),
        ),
        migrations.AddField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('Food', '食'), ('Clothing', '衣'), ('Accommodation', '住'), ('Transportation', '行'), ('Education', '育'), ('Entertainment', '樂'), ('Deposit', '存款'), ('Investment', '投資')], default='Food', max_length=30),
        ),
        migrations.AddField(
            model_name='incomes',
            name='category',
            field=models.CharField(choices=[('Food', '食'), ('Clothing', '衣'), ('Accommodation', '住'), ('Transportation', '行'), ('Education', '育'), ('Entertainment', '樂'), ('Deposit', '存款'), ('Investment', '投資')], default='Food', max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Food', '食'), ('Clothing', '衣'), ('Accommodation', '住'), ('Transportation', '行'), ('Education', '育'), ('Entertainment', '樂'), ('Deposit', '存款'), ('Investment', '投資')], default='Food', max_length=30),
        ),
        migrations.AddField(
            model_name='livingcost',
            name='category',
            field=models.CharField(choices=[('Food', '食'), ('Clothing', '衣'), ('Accommodation', '住'), ('Transportation', '行'), ('Education', '育'), ('Entertainment', '樂'), ('Deposit', '存款'), ('Investment', '投資')], default='Food', max_length=30),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 15, 19, 56, 38, 719944)),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 15, 19, 56, 38, 719456)),
        ),
    ]
