# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 21:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0030_auto_20171115_2129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('Food', '食'), ('Clothing', '衣'), ('Accommodation', '住'), ('Transportation', '行'), ('Education', '育'), ('Entertainment', '樂'), ('Deposit', '存款'), ('Investment', '投資')], default='食', max_length=30),
        ),
        migrations.AddField(
            model_name='incomes',
            name='category',
            field=models.CharField(choices=[('Food', '食'), ('Clothing', '衣'), ('Accommodation', '住'), ('Transportation', '行'), ('Education', '育'), ('Entertainment', '樂'), ('Deposit', '存款'), ('Investment', '投資')], default='食', max_length=30),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 15, 21, 36, 18, 883576)),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 15, 21, 36, 18, 883047)),
        ),
    ]
