# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0033_auto_20171115_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='budget',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='item',
            new_name='LC',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
