# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0034_auto_20171115_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomes',
            name='category',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget'),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget'),
        ),
    ]
