# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0038_backupcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='is_distributed',
            field=models.BooleanField(default=False),
        ),
    ]
