# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 00:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0040_auto_20171117_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='date',
        ),
        migrations.RemoveField(
            model_name='year',
            name='value',
        ),
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.IntegerField(default=2017, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
