# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0041_auto_20171117_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupcost',
            name='budget',
        ),
        migrations.AddField(
            model_name='debt',
            name='category',
            field=models.CharField(choices=[('Food', '食'), ('Clothing', '衣'), ('Accommodation', '住'), ('Transportation', '行'), ('Education', '育'), ('Entertainment', '樂')], default='Food', max_length=30),
        ),
        migrations.AddField(
            model_name='expenses',
            name='is_fulfill',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='BackupCost',
        ),
    ]
